export const PRODUCT_DATA_LOADING = "Product-data-loading"
export const PRODUCT_DATA_SUCCESS = "Product-data-success"
export const PRODUCT_DATA_FAILURE = "Product-data-failure"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM"